// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type File struct {
	ID              interface{}
	Name            interface{}
	Path            interface{}
	ThumbnailExists interface{}
	DateModified    interface{}
	DateCreated     interface{}
}
