// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type File struct {
	ID              sql.NullInt64
	Name            sql.NullString
	Path            sql.NullString
	ThumbnailExists sql.NullInt64
	DateModified    sql.NullInt64
	DateCreated     sql.NullInt64
}
